services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - react-app:/react-docker
      - ./src:/react-docker/src
      - ./public:/react-docker/public
      - node_modules:/react-docker/node_modules

    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
      - WATCHPACK_POLLING=true
    restart: unless-stopped

volumes:
  react-app:
  node_modules:
